bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os BUILD_WITH_MSVC CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX CXXCPP SIMAGE_MAJOR_VERSION SIMAGE_MINOR_VERSION SIMAGE_MICRO_VERSION SIMAGE_VERSION LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL MACOSX_10_2_TRUE MACOSX_10_2_FALSE SIMAGE_EXTRA_CPPFLAGS SIMAGE_EXTRA_CFLAGS SIMAGE_EXTRA_LDFLAGS SIMAGE_EXTRA_LIBS DSUFFIX CONFIG SUFFIX sim_ac_qt_cygpath SIMAGE_QIMAGE_SUPPORT_TRUE SIMAGE_QIMAGE_SUPPORT_FALSE SIMAGE_QUICKTIME_SUPPORT_TRUE SIMAGE_QUICKTIME_SUPPORT_FALSE SIMAGE_MPEG2ENC_SUPPORT_TRUE SIMAGE_MPEG2ENC_SUPPORT_FALSE SIMAGE_DEBUG_BUILD SIMAGE_DEBUG_BUILD_TRUE SIMAGE_DEBUG_BUILD_FALSE GUILE_PROG HAVE_GUILE_TRUE HAVE_GUILE_FALSE LIBFLAGS BUILD_WITH_MSVC_TRUE BUILD_WITH_MSVC_FALSE win_includedir win_libdir win_srcdir simage_configure_date COIN_COMPILER ac_compiler_gnu simage_src_dir SIMAGE_DSP_LIBS SIMAGE_DSP_INCS SIMAGE_DSP_DEFS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os BUILD_WITH_MSVC CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX CXXCPP SIMAGE_MAJOR_VERSION SIMAGE_MINOR_VERSION SIMAGE_MICRO_VERSION SIMAGE_VERSION LT_CURRENT LT_REVISION LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL MACOSX_TRUE MACOSX_FALSE MACOSX_10_2FF_TRUE MACOSX_10_2FF_FALSE SIMAGE_EXTRA_CPPFLAGS SIMAGE_EXTRA_CFLAGS SIMAGE_EXTRA_LDFLAGS SIMAGE_EXTRA_LIBS DSUFFIX CONFIG SUFFIX sim_ac_qt_cygpath SIMAGE_QIMAGE_SUPPORT_TRUE SIMAGE_QIMAGE_SUPPORT_FALSE SIMAGE_QUICKTIME_SUPPORT_TRUE SIMAGE_QUICKTIME_SUPPORT_FALSE SIMAGE_MPEG2ENC_SUPPORT_TRUE SIMAGE_MPEG2ENC_SUPPORT_FALSE SIMAGE_DEBUG_BUILD SIMAGE_DEBUG_BUILD_TRUE SIMAGE_DEBUG_BUILD_FALSE GUILE_PROG HAVE_GUILE_TRUE HAVE_GUILE_FALSE LIBFLAGS BUILD_WITH_MSVC_TRUE BUILD_WITH_MSVC_FALSE win_includedir win_libdir win_srcdir simage_configure_date COIN_COMPILER ac_compiler_gnu simage_src_dir SIMAGE_DSP_LIBS SIMAGE_DSP_INCS SIMAGE_DSP_DEFS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4404,12 +4404,25 @@ fi
 
 
 
+# Detect Mac OS X in general
 case $host_os in
-darwin6.* ) sim_ac_macosx_10_2=true ;;
-* )         sim_ac_macosx_10_2=false ;;
+darwin* )
+  sim_ac_macosx=true
+  # Check for Mac OS 10.2 or 10.3
+  case $host_os in
+  darwin[67].* )
+    sim_ac_macosx_10_2ff=true
+    ;;
+  * )
+    sim_ac_macosx_10_2ff=false
+    ;;
+  esac
+  ;;
+  * )
+  sim_ac_macosx=false ;;
 esac
 
-if test x"$sim_ac_macosx_10_2" = x"true"; then
+if test x"$sim_ac_macosx_10_2ff" = x"true"; then
   # Defines how undefined symbols are handled (used in libtool.m4)
   LD_TWOLEVEL_NAMESPACE=1
 fi
@@ -4962,7 +4975,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4965 "configure"' > conftest.$ac_ext
+  echo '#line 4978 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5573,7 +5586,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5576:" \
+echo "$as_me:5589:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6584,11 +6597,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6587: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6600: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6591: \$? = $ac_status" >&5
+   echo "$as_me:6604: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6816,11 +6829,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6819: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6832: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6823: \$? = $ac_status" >&5
+   echo "$as_me:6836: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6883,11 +6896,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6886: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6899: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6890: \$? = $ac_status" >&5
+   echo "$as_me:6903: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8895,7 +8908,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8898 "configure"
+#line 8911 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8993,7 +9006,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8996 "configure"
+#line 9009 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11127,11 +11140,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11130: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11143: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11134: \$? = $ac_status" >&5
+   echo "$as_me:11147: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11194,11 +11207,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11197: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11210: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11201: \$? = $ac_status" >&5
+   echo "$as_me:11214: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12437,7 +12450,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12440 "configure"
+#line 12453 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12535,7 +12548,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12538 "configure"
+#line 12551 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13357,11 +13370,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13360: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13373: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13364: \$? = $ac_status" >&5
+   echo "$as_me:13377: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13424,11 +13437,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13427: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13440: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13431: \$? = $ac_status" >&5
+   echo "$as_me:13444: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15364,11 +15377,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15367: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15380: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15371: \$? = $ac_status" >&5
+   echo "$as_me:15384: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15596,11 +15609,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15599: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15612: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15603: \$? = $ac_status" >&5
+   echo "$as_me:15616: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15663,11 +15676,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15666: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15679: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15670: \$? = $ac_status" >&5
+   echo "$as_me:15683: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17675,7 +17688,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17678 "configure"
+#line 17691 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17773,7 +17786,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17776 "configure"
+#line 17789 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18783,12 +18796,22 @@ fi
 
 
 
-if $sim_ac_macosx_10_2; then
-  MACOSX_10_2_TRUE=
-  MACOSX_10_2_FALSE='#'
+if $sim_ac_macosx; then
+  MACOSX_TRUE=
+  MACOSX_FALSE='#'
 else
-  MACOSX_10_2_TRUE='#'
-  MACOSX_10_2_FALSE=
+  MACOSX_TRUE='#'
+  MACOSX_FALSE=
+fi
+
+
+
+if $sim_ac_macosx_10_2ff; then
+  MACOSX_10_2FF_TRUE=
+  MACOSX_10_2FF_FALSE='#'
+else
+  MACOSX_10_2FF_TRUE='#'
+  MACOSX_10_2FF_FALSE=
 fi
 
 
@@ -18851,12 +18874,8 @@ fi;
 # 20020104 larsa
 if test x"$enable_symbols" = x"no"; then
   # CPPFLAGS="`echo $CPPFLAGS | sed 's/-g\>//'`"
-  CFLAGS="`echo $CFLAGS | sed 's/ -g //'`"
-  CFLAGS="`echo $CFLAGS | sed 's/^-g//'`"
-  CFLAGS="`echo $CFLAGS | sed 's/-g$//'`"
-  CXXFLAGS="`echo $CXXFLAGS | sed 's/ -g //'`"
-  CXXFLAGS="`echo $CXXFLAGS | sed 's/^-g//'`"
-  CXXFLAGS="`echo $CXXFLAGS | sed 's/-g$//'`"
+  CFLAGS="`echo $CFLAGS | sed 's/ -g //' | sed 's/^-g //' | sed 's/ -g$//'`"
+  CXXFLAGS="`echo $CXXFLAGS | sed 's/ -g //' | sed 's/^-g //' | sed 's/ -g$//'`"
 fi
 
 
@@ -19536,8 +19555,6 @@ echo $ECHO_N "checking value of the QTDIR environment variable... $ECHO_C" >&6
     if test x"$sim_ac_qtdir" = x""; then
       echo "$as_me:$LINENO: result: empty" >&5
 echo "${ECHO_T}empty" >&6
-      { echo "$as_me:$LINENO: WARNING: QTDIR environment variable not set -- this might be an indication of a problem" >&5
-echo "$as_me: WARNING: QTDIR environment variable not set -- this might be an indication of a problem" >&2;}
     else
       echo "$as_me:$LINENO: result: $sim_ac_qtdir" >&5
 echo "${ECHO_T}$sim_ac_qtdir" >&6
@@ -19999,7 +20016,14 @@ echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
       ##   (update: "ws2_32.lib" seems to be a new dependency for Qt 3.1.2)
       ##
       ## * "-lqt-mt-eval": the Qt/Mac evaluation version
+      ##
+      ## * "-lqt-mtnc{version}": the non-commercial Qt version that
+      ##   comes on the CD with the book "C++ Gui Programming with Qt 3"
+      ##   (version==321 there)
 
+      ## FIXME: could probably improve check to not have to go through
+      ## all of the above. See bug item #028 in SoQt/BUGS.txt.
+      ## 20040805 mortene.
 
       sim_ac_qt_suffix=
       if $sim_ac_qt_debug; then
@@ -20025,7 +20049,8 @@ echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
             "-lqt -lqtmain -lgdi32" \
             "-lqt${sim_ac_qt_version}${sim_ac_qt_suffix} -lqtmain -lgdi32" \
             "-lqt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32" \
-            "-lqt-mt-eval"
+            "-lqt-mt-eval" \
+            "-lqt-mtnc${sim_ac_qt_version}"
         do
           if test "x$sim_ac_qt_libs" = "xUNRESOLVED"; then
             CPPFLAGS="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop $sim_ac_save_cppflags"
@@ -20136,6 +20161,10 @@ echo "${ECHO_T}ok" >&6
     sim_ac_qimage_support=true
 
   else
+    if test -z "$QTDIR"; then
+      { echo "$as_me:$LINENO: WARNING: QTDIR environment variable not set -- this might be an indication of a problem" >&5
+echo "$as_me: WARNING: QTDIR environment variable not set -- this might be an indication of a problem" >&2;}
+    fi
     CPPFLAGS=$sim_ac_save_cppflags
     LDFLAGS=$sim_ac_save_ldflags
     LIBS=$sim_ac_save_libs
@@ -21974,7 +22003,7 @@ else
       sim_ac_lsf_libs="-lsndfile -llibsndfile"
       sim_ac_lsfchk_hit=false
       for sim_ac_lsf_lib in "" $sim_ac_lsf_libs; do
-        if ! $sim_ac_lsfchk_hit; then
+        if $sim_ac_lsfchk_hit; then :; else
           LIBS="$sim_ac_lsf_lib $sim_ac_save_libs"
           cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -22930,7 +22959,12 @@ else
   eval "simage_configure_date=\"`date +%Y%m%d`\""
 
 
-  COIN_COMPILER="$CC"
+
+  # Mac OS X needs to call gcc as g++ when linking C++
+  case $host_os in
+  darwin*) COIN_COMPILER="$CXX";;
+  *) COIN_COMPILER="$CC";;
+  esac
 fi
 
 
@@ -23155,10 +23189,17 @@ echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${MACOSX_10_2_TRUE}" && test -z "${MACOSX_10_2_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"MACOSX_10_2\" was never defined.
+if test -z "${MACOSX_TRUE}" && test -z "${MACOSX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MACOSX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"MACOSX_10_2\" was never defined.
+echo "$as_me: error: conditional \"MACOSX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MACOSX_10_2FF_TRUE}" && test -z "${MACOSX_10_2FF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MACOSX_10_2FF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MACOSX_10_2FF\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23817,8 +23858,10 @@ s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
-s,@MACOSX_10_2_TRUE@,$MACOSX_10_2_TRUE,;t t
-s,@MACOSX_10_2_FALSE@,$MACOSX_10_2_FALSE,;t t
+s,@MACOSX_TRUE@,$MACOSX_TRUE,;t t
+s,@MACOSX_FALSE@,$MACOSX_FALSE,;t t
+s,@MACOSX_10_2FF_TRUE@,$MACOSX_10_2FF_TRUE,;t t
+s,@MACOSX_10_2FF_FALSE@,$MACOSX_10_2FF_FALSE,;t t
 s,@SIMAGE_EXTRA_CPPFLAGS@,$SIMAGE_EXTRA_CPPFLAGS,;t t
 s,@SIMAGE_EXTRA_CFLAGS@,$SIMAGE_EXTRA_CFLAGS,;t t
 s,@SIMAGE_EXTRA_LDFLAGS@,$SIMAGE_EXTRA_LDFLAGS,;t t
