Cosmetic changes (verbose commands on make and make install/uninstall).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2604,17 +2604,17 @@ END
 # If we don't find an include directive, just comment out the code.
 echo "$as_me:2605: checking for style of include used by $am_make" >&5
 echo $ECHO_N "checking for style of include used by $am_make... $ECHO_C" >&6
-AMINCLUDE='#'
+_am_include='#'
 for am_inc in include .include; do
    echo "$am_inc confinc" > confmf
    if test "`$am_make -f confmf 2> /dev/null`" = "done"; then
-      AMINCLUDE=$am_inc
+      _am_include=$am_inc
       break
    fi
 done
 
-echo "$as_me:2616: result: $AMINCLUDE" >&5
-echo "${ECHO_T}$AMINCLUDE" >&6
+echo "$as_me:2616: result: $_am_include" >&5
+echo "${ECHO_T}$_am_include" >&6
 rm -f confinc confmf
 
 # test to see if srcdir already configured
@@ -4725,6 +4725,9 @@ if $BUILD_WITH_MSVC; then
   if $SIMAGE_STATIC; then
     LIBFLAGS="-LIB"
     LIBFLAGS="$LIBFLAGS /OUT:simage$SIMAGE_MAJOR_VERSION$SUFFIX.lib"
+    SIMAGE_EXTRA_CPPFLAGS="-I$includedir"
+    SIMAGE_EXTRA_LDFLAGS="-L$libdir"
+    SIMAGE_EXTRA_LIBS=
   else
     LIBFLAGS="-DLL /INCREMENTAL:NO"
     if test x"$enable_debug" = xno; then
@@ -4849,7 +4852,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4852: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4855: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<\_ACEOF
 #! /bin/sh
@@ -4906,7 +4909,7 @@ if test -x conftest.file >/dev/null 2>&1; then
 elif test -f conftest.file >/dev/null 2>&1; then
   as_executable_p="test -f"
 else
-  { { echo "$as_me:4909: error: cannot check whether a file is executable on this system" >&5
+  { { echo "$as_me:4912: error: cannot check whether a file is executable on this system" >&5
 echo "$as_me: error: cannot check whether a file is executable on this system" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5049,7 +5052,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5052: error: ambiguous option: $1
+    { { echo "$as_me:5055: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5077,12 +5080,12 @@ Try \`$0 --help' for more information." >&2;}
   'include/simage.h' ) CONFIG_HEADERS="$CONFIG_HEADERS include/simage.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:5080: error: unrecognized option: $1
+  -*) { { echo "$as_me:5083: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:5085: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:5088: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5229,7 +5232,7 @@ s,@AMDEPBACKSLASH@,$AMDEPBACKSLASH,;t t
 s,@DEPDIR@,$DEPDIR,;t t
 s,@CPP@,$CPP,;t t
 s,@CPPFLAGS@,$CPPFLAGS,;t t
-s,@AMINCLUDE@,$AMINCLUDE,;t t
+s,@_am_include@,$_am_include,;t t
 s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
@@ -5381,7 +5384,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5384: creating $ac_file" >&5
+    { echo "$as_me:5387: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5399,7 +5402,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:5402: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5405: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5412,7 +5415,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5415: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5418: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5473,7 +5476,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5476: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5479: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5484,7 +5487,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:5487: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5490: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5497,7 +5500,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5500: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5503: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5614,7 +5617,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5617: $ac_file is unchanged" >&5
+      { echo "$as_me:5620: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -5761,7 +5764,7 @@ done
 fi
 
 echo ""
-echo "Done.  Now run make install to build $PACKAGE"
+echo "Done.  Now run make install to build $PACKAGE."
 echo ""
 
 # **************************************************************************
