Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1024,6 +1024,7 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-debug          compile in debug mode [default=yes]
   --enable-symbols        include symbol debug information [default=yes]
+  --enable-qt-debug       win32: link with debug versions of Qt libraries
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1693,29 +1694,29 @@ if test "${with_msvcrt+set}" = set; then
     ;;
   multithread-static | mt | /mt | libcmt | libcmt\.lib )
     sim_ac_msvcrt=multithread-static
-    sim_ac_msvcrt_CFLAGS="/MT"
-    sim_ac_msvcrt_CXXFLAGS="/MT"
+    sim_ac_msvcrt_CFLAGS="/MT -D_MT -D_DLL"
+    sim_ac_msvcrt_CXXFLAGS="/MT -D_MT -D_DLL"
     sim_ac_msvcrt_LIBLDFLAGS="/LINK /NODEFAULTLIB:libc"
     sim_ac_msvcrt_LIBLIBS="-llibcmt"
     ;;
   multithread-static-debug | mtd | /mtd | libcmtd | libcmtd\.lib )
     sim_ac_msvcrt=multithread-static-debug
-    sim_ac_msvcrt_CFLAGS="/MTd"
-    sim_ac_msvcrt_CXXFLAGS="/MTd"
+    sim_ac_msvcrt_CFLAGS="/MTd -D_MT -D_DLL"
+    sim_ac_msvcrt_CXXFLAGS="/MTd -D_MT -D_DLL"
     sim_ac_msvcrt_LIBLDFLAGS="/NODEFAULTLIB:libc"
     sim_ac_msvcrt_LIBLIBS="-llibcmtd"
     ;;
   multithread-dynamic | md | /md | msvcrt | msvcrt\.lib )
     sim_ac_msvcrt=multithread-dynamic
-    sim_ac_msvcrt_CFLAGS=""
-    sim_ac_msvcrt_CXXFLAGS=""
+    sim_ac_msvcrt_CFLAGS="/MD -D_DLL"
+    sim_ac_msvcrt_CXXFLAGS="/MD -D_DLL"
     sim_ac_msvcrt_LIBLDFLAGS="/LINK /NODEFAULTLIB:libc"
     sim_ac_msvcrt_LIBLIBS="-lmsvcrt"
     ;;
   multithread-dynamic-debug | mdd | /mdd | msvcrtd | msvcrtd\.lib )
     sim_ac_msvcrt=multithread-dynamic-debug
-    sim_ac_msvcrt_CFLAGS="/MDd"
-    sim_ac_msvcrt_CXXFLAGS="/MDd"
+    sim_ac_msvcrt_CFLAGS="/MDd -D_DLL"
+    sim_ac_msvcrt_CXXFLAGS="/MDd -D_DLL"
     sim_ac_msvcrt_LIBLDFLAGS="/LINK /NODEFAULTLIB:libc"
     sim_ac_msvcrt_LIBLIBS="-lmsvcrtd"
     ;;
@@ -5211,7 +5212,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5214 "configure"' > conftest.$ac_ext
+  echo '#line 5215 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5747,7 +5748,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5750: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5751: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7540,7 +7541,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7543 "configure"
+#line 7544 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7638,7 +7639,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7641 "configure"
+#line 7642 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8419,10 +8420,12 @@ else
   enable_symbols=yes
 fi;
 
+# FIXME: don't mangle options like -fno-gnu-linker and -fvolatile-global
+# 20020104 larsa
 if test x"$enable_symbols" = x"no"; then
-  CFLAGS="`echo $CFLAGS | sed 's/-g//'`"
-  CPPFLAGS="`echo $CPPFLAGS | sed 's/-g//'`"
-  CXXFLAGS="`echo $CXXFLAGS | sed 's/-g//'`"
+  # CPPFLAGS="`echo $CPPFLAGS | sed 's/-g[0-9]//'`"
+  CFLAGS="`echo $CFLAGS | sed 's/-g0-9?//'`"
+  CXXFLAGS="`echo $CXXFLAGS | sed 's/-g0-9?//'`"
 fi
 
 
@@ -8678,6 +8681,17 @@ else
   with_qt=yes
 fi;
 
+# Check whether --enable-qt-debug or --disable-qt-debug was given.
+if test "${enable_qt_debug+set}" = set; then
+  enableval="$enable_qt_debug"
+  case $enableval in
+  yes | true ) sim_ac_qt_debug=true ;;
+  *) sim_ac_qt_debug=false ;;
+  esac
+else
+  sim_ac_qt_debug=false
+fi;
+
 sim_ac_qt_avail=no
 
 if test x"$with_qt" != xno; then
@@ -8820,49 +8834,8 @@ fi
 echo "$as_me: WARNING: the \`\`moc'' Qt pre-processor tool not found" >&2;}
   else
 
-  if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for qglobal.h" >&5
-echo $ECHO_N "checking for qglobal.h... $ECHO_C" >&6
-if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qglobal_h" >&5
-echo "${ECHO_T}$ac_cv_header_qglobal_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking qglobal.h usability" >&5
-echo $ECHO_N "checking qglobal.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-$ac_includes_default
-#include <qglobal.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_header_compiler=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
+  sim_ac_qglobal=false
 
-# Is the header present?
-echo "$as_me:$LINENO: checking qglobal.h presence" >&5
-echo $ECHO_N "checking qglobal.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -8885,49 +8858,60 @@ else
   ac_cpp_err=yes
 fi
 if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
+  ac_cv_header_qglobal_h=yes
 else
   echo "$as_me: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  ac_header_preproc=no
+  ac_cv_header_qglobal_h=no
 fi
 rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: qglobal.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: qglobal.h: proceeding with the preprocessor's result" >&2;};;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: qglobal.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: qglobal.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: qglobal.h: proceeding with the preprocessor's result" >&2;};;
-esac
-echo "$as_me:$LINENO: checking for qglobal.h" >&5
-echo $ECHO_N "checking for qglobal.h... $ECHO_C" >&6
-if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_qglobal_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qglobal_h" >&5
-echo "${ECHO_T}$ac_cv_header_qglobal_h" >&6
-
-fi
 if test $ac_cv_header_qglobal_h = yes; then
   sim_ac_qglobal=true
 else
-  { echo "$as_me:$LINENO: WARNING: header file qglobal.h not found" >&5
-echo "$as_me: WARNING: header file qglobal.h not found" >&2;}
-                   sim_ac_qglobal=false
+  # Debian Linux has the Qt-dev installation headers in a separate subdir.
+    sim_ac_debian_qtheaders=/usr/include/qt
+     if test -d $sim_ac_debian_qtheaders; then
+       sim_ac_qt_incflags="-I$sim_ac_debian_qtheaders $sim_ac_qt_incflags"
+       CPPFLAGS="-I$sim_ac_debian_qtheaders $CPPFLAGS"
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <qglobal.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
 fi
+if test -z "$ac_cpp_err"; then
+  ac_cv_header_qglobal_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_cv_header_qglobal_h=no
+fi
+rm -f conftest.err conftest.$ac_ext
+if test $ac_cv_header_qglobal_h = yes; then
+  sim_ac_qglobal=true
+fi
+
+
+
+     fi
+fi
+
 
 
 
@@ -8945,6 +8929,15 @@ EOF
   # because at least the Solaris/CC preprocessor adds extra spaces before and
   # after the trailing semicolon.
   sim_ac_qt_version=`$CXXCPP $CPPFLAGS conftest.c | grep '^int VerQt' | sed 's%^int VerQt = %%' | sed 's% *; *$%%'`
+
+  case $sim_ac_qt_version in
+  0x* )
+    sim_ac_qt_version=`echo $sim_ac_qt_version | sed -e 's/^0x.\(.\).\(.\).\(.\)/\1\2\3/;'`
+    ;;
+  * )
+    # nada
+    ;;
+  esac
 
   rm -f conftest.c
   echo "$as_me:$LINENO: result: $sim_ac_qt_version" >&5
@@ -9023,59 +9016,27 @@ fi
   if test x"$MOC" != xfalse; then
     # Do not cache the result, as we might need to play tricks with
     # CPPFLAGS under MSWin.
-    echo "$as_me:$LINENO: checking for Qt library devkit" >&5
-echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
 
-    ## Test all known possible combinations of linking against the
-    ## Troll Tech Qt library:
-    ##
-    ## * "-lqt-gl" links against the standard Debian version of the
-    ##   Qt library with embedded QGL
-    ##
-    ## * "-lqt" should work for most UNIX(-derived) platforms on
-    ##   dynamic and static linking with the non-mtsafe library
-    ##
-    ## * "-lqt-mt" should work for most UNIX(-derived) platforms on
-    ##   dynamic and static linking with the mtsafe library
-    ##
-    ## * "-lqt{version} -lqtmain -lgdi32" w/QT_DLL defined should
-    ##   cover dynamic Enterprise Edition linking on Win32 platforms
-    ##
-    ## * "-lqt-mt{version} -lqtmain -lgdi32" w/QT_DLL defined should
-    ##   cover dynamic multi-thread Enterprise Edition linking on Win32
-    ##   platforms
-    ##
-    ## * "-lqt-mt{version}nc -lqtmain -lgdi32" w/QT_DLL defined should
-    ##   cover dynamic Non-Commercial Edition linking on Win32 platforms
-    ##
-    ## * "-lqt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32" should cover static
-    ##   linking on Win32 platforms
-    ##
-    ## * "-lqt-mt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32 -lwinspool -lwinmm"; do
-    ##   added for the benefit of the Qt 3.0.0 Evaliation Version
-    ##
-
-    # FIXME: it would be extremely helpful if one could override the cppflags
-    # and libs-checking with environment variables. Then people wouldn't get
-    # completely stuck when the check fails -- we can just take a look at the
+    # It should be helpful to be able to override the libs-checking with
+    # environment variables. Then people won't get completely stuck
+    # when the check fails -- we can just take a look at the
     # config.log and give them advice on how to proceed with no updates
-    # necessary. 20020311 mortene.
+    # necessary.
+    #
+    # (Note also that this makes it possible to select whether to use the
+    # mt-safe or the "standard" Qt library if both are installed on the
+    # user's system.)
+    #
+    # mortene.
 
-    # FIXME: it should be possible to select whether to use the mt-safe or
-    # the "standard" Qt library if both are installed on the user's system.
-    # 20020311 mortene.
+    if test x"$CONFIG_QTLIBS" != x""; then
+      echo "$as_me:$LINENO: checking for Qt linking with $CONFIG_QTLIBS" >&5
+echo $ECHO_N "checking for Qt linking with $CONFIG_QTLIBS... $ECHO_C" >&6
 
-    # FIXME: this link test doesn't detect all link problems...
-    # (UPDATE 20020311 mortene: jeez, that was a very helpful FIXME. Lars?)
-    for sim_ac_qt_cppflags_loop in "" "-DQT_DLL"; do
-      for sim_ac_qt_libcheck in "-lqt-gl" "-lqt" "-lqt-mt" \
-          "-lqt${sim_ac_qt_version} -lqtmain -lgdi32" \
-          "-lqt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32" \
-          "-lqt-mt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32 -lwinspool -lwinmm"; do
-        if test "x$sim_ac_qt_libs" = "xUNRESOLVED"; then
-          CPPFLAGS="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop $sim_ac_save_cppflags"
-          LIBS="$sim_ac_qt_libcheck $sim_ac_save_libs"
-          cat >conftest.$ac_ext <<_ACEOF
+      for sim_ac_qt_cppflags_loop in "" "-DQT_DLL"; do
+        CPPFLAGS="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop $sim_ac_save_cppflags"
+        LIBS="$CONFIG_QTLIBS $sim_ac_save_libs"
+        cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 #include <qapplication.h>
@@ -9088,8 +9049,8 @@ echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
 int
 main ()
 {
-int dummy=0;
-                       qApp->exit(0);
+qApp = NULL; /* QT_DLL must be defined for assignment to global variables to work */
+                     qApp->exit(0);
   ;
   return 0;
 }
@@ -9106,20 +9067,76 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_ac_qt_libs="$sim_ac_qt_libcheck"
-                       sim_ac_qt_cppflags="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop"
+  sim_ac_qt_libs="$CONFIG_QTLIBS"
+                     sim_ac_qt_cppflags="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop"
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-        fi
       done
-    done
 
-    if test "x$sim_ac_qt_libs" = "xUNRESOLVED"; then
-      for sim_ac_qt_cppflags_loop in "-DQT_DLL"; do
-        for sim_ac_qt_libcheck in "-lqt-mt${sim_ac_qt_version} -lqtmain -lgdi32" "-lqt-mt${sim_ac_qt_version}nc -lqtmain -lgdi32"; do
+      if test "x$sim_ac_qt_libs" = "xUNRESOLVED"; then
+        echo "$as_me:$LINENO: result: failed!" >&5
+echo "${ECHO_T}failed!" >&6
+      else
+        echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+      fi
+
+    else
+      echo "$as_me:$LINENO: checking for Qt library devkit" >&5
+echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
+
+      ## Test all known possible combinations of linking against the
+      ## Troll Tech Qt library:
+      ##
+      ## * "-lqt-gl": links against the standard Debian version of the
+      ##   Qt library with embedded QGL
+      ##
+      ## * "-lqt": should work for most UNIX(-derived) platforms on
+      ##   dynamic and static linking with the non-mtsafe library
+      ##
+      ## * "-lqt-mt": should work for most UNIX(-derived) platforms on
+      ##   dynamic and static linking with the mtsafe library
+      ##
+      ## * "-lqt{version} -lqtmain -lgdi32": w/QT_DLL defined should
+      ##   cover dynamic Enterprise Edition linking on Win32 platforms
+      ##
+      ## * "-lqt -lqtmain -lgdi32": ...unless the {version} suffix is missing,
+      ##   which we've had reports about
+      ##
+      ## * "-lqt-mt{version} -lqtmain -lgdi32": w/QT_DLL defined should
+      ##   cover dynamic multi-thread Enterprise Edition linking on Win32
+      ##   platforms
+      ##
+      ## * "-lqt-mt{version}nc -lqtmain -lgdi32": w/QT_DLL defined should
+      ##   cover dynamic Non-Commercial Edition linking on Win32 platforms
+      ##
+      ## * "-lqt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32": should cover
+      ##   static linking on Win32 platforms
+      ##
+      ## * "-lqt-mt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32 -lwinspool -lwinmm":
+      ##   added for the benefit of the Qt 3.0.0 Evaluation Version
+      ##
+
+      sim_ac_qt_suffix=
+      if $sim_ac_qt_debug; then
+        sim_ac_qt_suffix=d
+      fi
+
+      for sim_ac_qt_cppflags_loop in "" "-DQT_DLL"; do
+        for sim_ac_qt_libcheck in \
+            "-lqt-gl" \
+            "-lqt" \
+            "-lqt-mt" \
+            "-lqt -lqtmain -lgdi32" \
+            "-lqt${sim_ac_qt_version}${sim_ac_qt_suffix} -lqtmain -lgdi32" \
+            "-lqt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32" \
+            "-lqt-mt -luser32 -lole32 -limm32 -lcomdlg32 -lgdi32 -lwinspool -lwinmm" \
+            "-lqt-mt${sim_ac_qt_version}${sim_ac_qt_suffix} -lqtmain -lgdi32" \
+            "-lqt-mt${sim_ac_qt_version}nc${sim_ac_qt_suffix} -lqtmain -lgdi32"
+        do
           if test "x$sim_ac_qt_libs" = "xUNRESOLVED"; then
             CPPFLAGS="$sim_ac_qt_incflags $sim_ac_qt_cppflags_loop $sim_ac_save_cppflags"
             LIBS="$sim_ac_qt_libcheck $sim_ac_save_libs"
@@ -9136,7 +9153,7 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 int
 main ()
 {
-int dummy=0;
+qApp = NULL; /* QT_DLL must be defined for assignment to global variables to work */
                          qApp->exit(0);
   ;
   return 0;
@@ -9164,13 +9181,16 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
           fi
         done
       done
-    fi
 
-    echo "$as_me:$LINENO: result: $sim_ac_qt_cppflags $sim_ac_qt_libs" >&5
+      echo "$as_me:$LINENO: result: $sim_ac_qt_cppflags $sim_ac_qt_libs" >&5
 echo "${ECHO_T}$sim_ac_qt_cppflags $sim_ac_qt_libs" >&6
+    fi
   fi
 
-  fi # sim_ac_qglobal = TRUE
+  else # sim_ac_qglobal = false
+   { echo "$as_me:$LINENO: WARNING: header file qglobal.h not found, can not compile Qt code" >&5
+echo "$as_me: WARNING: header file qglobal.h not found, can not compile Qt code" >&2;}
+  fi
   fi # MOC = false
 
   if test ! x"$sim_ac_qt_libs" = xUNRESOLVED; then
