Detect libtiff properly under Win32. Thanks to larsa for holding my hand while I fixed the m4-macro :)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.65 .
+# From configure.in Revision: 1.66 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.50 for simage v1.1.2.
 #
@@ -4363,6 +4363,40 @@ else
 cat conftest.$ac_ext >&5
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  if test x"$sim_ac_have_libtiff" = xfalse; then
+    sim_ac_libtiff_libs="-l$sim_ac_libtiff_name -luser32"
+    LIBS="$sim_ac_libtiff_libs $sim_ac_libtiff_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line 4370 "configure"
+#include "confdefs.h"
+#include <tiffio.h>
+int
+main ()
+{
+(void)TIFFOpen(0L, 0L);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:4382: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:4385: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:4388: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:4391: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_have_libtiff=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  fi
   CPPFLAGS=$sim_ac_libtiff_save_CPPFLAGS
   LDFLAGS=$sim_ac_libtiff_save_LDFLAGS
   LIBS=$sim_ac_libtiff_save_LIBS
@@ -4375,7 +4409,7 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 esac
 if $sim_ac_want_libtiff; then
   if $sim_ac_have_libtiff; then
-    echo "$as_me:4378: result: success ($sim_ac_libtiff_libs)" >&5
+    echo "$as_me:4412: result: success ($sim_ac_libtiff_libs)" >&5
 echo "${ECHO_T}success ($sim_ac_libtiff_libs)" >&6
 
 cat >>confdefs.h <<\EOF
@@ -4395,7 +4429,7 @@ else
 fi
 
   else
-    echo "$as_me:4398: result: failure" >&5
+    echo "$as_me:4432: result: failure" >&5
 echo "${ECHO_T}failure" >&6
 
   if test x${sim_ac_configuration_settings+set} != xset; then
@@ -4406,7 +4440,7 @@ fi
 
   fi
 else
-  echo "$as_me:4409: result: disabled" >&5
+  echo "$as_me:4443: result: disabled" >&5
 echo "${ECHO_T}disabled" >&6
 
   if test x${sim_ac_configuration_settings+set} != xset; then
@@ -4437,7 +4471,7 @@ if test "${with_targa+set}" = set; then
   case $withval in
   yes | "") sim_ac_want_tga=true ;;
   no)       sim_ac_want_tga=false ;;
-  *)        { { echo "$as_me:4440: error: bad value \"$withval\" for --with-targa" >&5
+  *)        { { echo "$as_me:4474: error: bad value \"$withval\" for --with-targa" >&5
 echo "$as_me: error: bad value \"$withval\" for --with-targa" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -4482,7 +4516,7 @@ if test "${with_rgb+set}" = set; then
   case $withval in
   yes | "") sim_ac_want_rgb=true ;;
   no)       sim_ac_want_rgb=false ;;
-  *)        { { echo "$as_me:4485: error: bad value \"$withval\" for --with-rgb" >&5
+  *)        { { echo "$as_me:4519: error: bad value \"$withval\" for --with-rgb" >&5
 echo "$as_me: error: bad value \"$withval\" for --with-rgb" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -4527,7 +4561,7 @@ if test "${with_pic+set}" = set; then
   case $withval in
   yes | "") sim_ac_want_pic=true ;;
   no)       sim_ac_want_pic=false ;;
-  *)        { { echo "$as_me:4530: error: bad value \"$withval\" for --with-pic" >&5
+  *)        { { echo "$as_me:4564: error: bad value \"$withval\" for --with-pic" >&5
 echo "$as_me: error: bad value \"$withval\" for --with-pic" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -4572,7 +4606,7 @@ if test "${with_xwd+set}" = set; then
   case $withval in
   yes | "") sim_ac_want_xwd=true ;;
   no)       sim_ac_want_xwd=false ;;
-  *)        { { echo "$as_me:4575: error: bad value \"$withval\" for --with-xwd" >&5
+  *)        { { echo "$as_me:4609: error: bad value \"$withval\" for --with-xwd" >&5
 echo "$as_me: error: bad value \"$withval\" for --with-xwd" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -4617,7 +4651,7 @@ if test "${with_mpeg2enc+set}" = set; then
   case $withval in
   yes | "") sim_ac_want_mpeg2enc=true ;;
   no)       sim_ac_want_mpeg2enc=false ;;
-  *)        { { echo "$as_me:4620: error: bad value \"$withval\" for --with-mpeg2enc" >&5
+  *)        { { echo "$as_me:4654: error: bad value \"$withval\" for --with-mpeg2enc" >&5
 echo "$as_me: error: bad value \"$withval\" for --with-mpeg2enc" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
@@ -4674,23 +4708,23 @@ fi
 for ac_header in dlfcn.h
 do
 ac_ac_Header=`echo "ac_cv_header_$ac_header" | $ac_tr_sh`
-echo "$as_me:4677: checking for $ac_header" >&5
+echo "$as_me:4711: checking for $ac_header" >&5
 echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
 if eval "test \"\${$ac_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 4683 "configure"
+#line 4717 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 _ACEOF
-if { (eval echo "$as_me:4687: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:4721: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:4693: \$? = $ac_status" >&5
+  echo "$as_me:4727: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -4709,7 +4743,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:4712: result: `eval echo '${'$ac_ac_Header'}'`" >&5
+echo "$as_me:4746: result: `eval echo '${'$ac_ac_Header'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$ac_ac_Header'}'`" >&6
 if test `eval echo '${'$ac_ac_Header'}'` = yes; then
   cat >>confdefs.h <<EOF
@@ -4725,7 +4759,7 @@ HAVE_GUILE=false
 if $sim_ac_have_dlfcn_h; then
   # Extract the first word of "guile", so it can be a program name with args.
 set dummy guile; ac_word=$2
-echo "$as_me:4728: checking for $ac_word" >&5
+echo "$as_me:4762: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_GUILE_PROG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4742,7 +4776,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_GUILE_PROG="$ac_dir/$ac_word"
-   echo "$as_me:4745: found $ac_dir/$ac_word" >&5
+   echo "$as_me:4779: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -4754,10 +4788,10 @@ fi
 GUILE_PROG=$ac_cv_path_GUILE_PROG
 
 if test -n "$GUILE_PROG"; then
-  echo "$as_me:4757: result: $GUILE_PROG" >&5
+  echo "$as_me:4791: result: $GUILE_PROG" >&5
 echo "${ECHO_T}$GUILE_PROG" >&6
 else
-  echo "$as_me:4760: result: no" >&5
+  echo "$as_me:4794: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -4766,23 +4800,23 @@ fi
 for ac_header in libguile.h guile/gh.h
 do
 ac_ac_Header=`echo "ac_cv_header_$ac_header" | $ac_tr_sh`
-echo "$as_me:4769: checking for $ac_header" >&5
+echo "$as_me:4803: checking for $ac_header" >&5
 echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
 if eval "test \"\${$ac_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 4775 "configure"
+#line 4809 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 _ACEOF
-if { (eval echo "$as_me:4779: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:4813: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:4785: \$? = $ac_status" >&5
+  echo "$as_me:4819: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -4801,7 +4835,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:4804: result: `eval echo '${'$ac_ac_Header'}'`" >&5
+echo "$as_me:4838: result: `eval echo '${'$ac_ac_Header'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$ac_ac_Header'}'`" >&6
 if test `eval echo '${'$ac_ac_Header'}'` = yes; then
   cat >>confdefs.h <<EOF
@@ -5181,7 +5215,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5184: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5218: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5357,7 +5391,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5360: error: ambiguous option: $1
+    { { echo "$as_me:5394: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5387,12 +5421,12 @@ Try \`$0 --help' for more information." >&2;}
   'include/simage.h' ) CONFIG_HEADERS="$CONFIG_HEADERS include/simage.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:5390: error: unrecognized option: $1
+  -*) { { echo "$as_me:5424: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:5395: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:5429: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5714,7 +5748,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5717: creating $ac_file" >&5
+    { echo "$as_me:5751: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5732,7 +5766,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5735: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5769: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5745,7 +5779,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5748: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5782: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5806,7 +5840,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5809: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5843: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5817,7 +5851,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5820: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5854: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5830,7 +5864,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5833: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5867: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5947,7 +5981,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5950: $ac_file is unchanged" >&5
+      { echo "$as_me:5984: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
