Properly set up -DSIMAGE_NOT_DLL flag for simage-config on Cygwin.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.68 .
+# From configure.in Revision: 1.69 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.50 for simage v1.2.1.
 #
@@ -5035,7 +5035,8 @@ LIBFLAGS=
 if $BUILD_WITH_MSVC; then
   if $SIMAGE_STATIC; then
     # static overrides shared
-    SIMAGE_EXTRA_CPPFLAGS="$SIMAGE_EXTRA_CPPFLAGS -DSIMAGE_NOT_DLL"
+    CPPFLAGS="$CPPFLAGS -DSIMAGE_NOT_DLL"
+    # SIMAGE_EXTRA_CPPFLAGS is updated further down
   else
     CPPFLAGS="-DSIMAGE_MAKE_DLL $CPPFLAGS"
     SIMAGE_EXTRA_CPPFLAGS="$SIMAGE_EXTRA_CPPFLAGS -DSIMAGE_DLL"
@@ -5046,7 +5047,7 @@ if $BUILD_WITH_MSVC; then
   if $SIMAGE_STATIC; then
     LIBFLAGS="-LIB"
     LIBFLAGS="$LIBFLAGS /OUT:simage$SIMAGE_MAJOR_VERSION$SUFFIX.lib"
-    SIMAGE_EXTRA_CPPFLAGS="-I$includedir"
+    SIMAGE_EXTRA_CPPFLAGS="-I$includedir -DSIMAGE_NOT_DLL"
     SIMAGE_EXTRA_LDFLAGS="-L$libdir"
     SIMAGE_EXTRA_LIBS=
   else
@@ -5182,7 +5183,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5185: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5186: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5358,7 +5359,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5361: error: ambiguous option: $1
+    { { echo "$as_me:5362: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5388,12 +5389,12 @@ Try \`$0 --help' for more information." >&2;}
   'include/simage.h' ) CONFIG_HEADERS="$CONFIG_HEADERS include/simage.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:5391: error: unrecognized option: $1
+  -*) { { echo "$as_me:5392: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:5396: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:5397: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5701,7 +5702,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5704: creating $ac_file" >&5
+    { echo "$as_me:5705: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5719,7 +5720,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5722: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5723: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5732,7 +5733,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5735: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5736: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5793,7 +5794,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5796: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5797: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5804,7 +5805,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5807: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5808: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5817,7 +5818,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5820: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5821: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5934,7 +5935,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5937: $ac_file is unchanged" >&5
+      { echo "$as_me:5938: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
