Set up CPPFLAGS etc for static lib.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5239,9 +5239,7 @@ fi
 
 if $BUILD_WITH_MSVC; then
   if $SIMAGE_STATIC; then
-    # static overrides shared
-    CPPFLAGS="$CPPFLAGS -DSIMAGE_NOT_DLL"
-    # SIMAGE_EXTRA_CPPFLAGS is updated further down
+    SIMAGE_EXTRA_CPPFLAGS="$SIMAGE_EXTRA_CPPFLAGS -DSIMAGE_NOT_DLL"
   else
     CPPFLAGS="-DSIMAGE_MAKE_DLL $CPPFLAGS"
     SIMAGE_EXTRA_CPPFLAGS="$SIMAGE_EXTRA_CPPFLAGS -DSIMAGE_DLL"
@@ -5252,9 +5250,6 @@ if $BUILD_WITH_MSVC; then
   if $SIMAGE_STATIC; then
     LIBFLAGS="-LIB"
     LIBFLAGS="$LIBFLAGS /OUT:simage$SIMAGE_MAJOR_VERSION$SUFFIX.lib"
-    SIMAGE_EXTRA_CPPFLAGS="-I$includedir -DSIMAGE_NOT_DLL"
-    SIMAGE_EXTRA_LDFLAGS="-L$libdir"
-    SIMAGE_EXTRA_LIBS=
   else
     LIBFLAGS="-DLL /INCREMENTAL:NO"
     case $enable_symbols in
@@ -5388,7 +5383,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5391: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5386: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5564,7 +5559,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5567: error: ambiguous option: $1
+    { { echo "$as_me:5562: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5583,7 +5578,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5586: error: unrecognized option: $1
+  -*) { { echo "$as_me:5581: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5646,7 +5641,7 @@ do
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   "include/simage.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/simage.h" ;;
-  *) { { echo "$as_me:5649: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5644: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5924,7 +5919,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5927: creating $ac_file" >&5
+    { echo "$as_me:5922: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5942,7 +5937,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5945: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5940: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5955,7 +5950,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5958: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5953: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6016,7 +6011,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6019: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6014: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6027,7 +6022,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6030: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6025: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6040,7 +6035,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6043: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6038: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6157,7 +6152,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6160: $ac_file is unchanged" >&5
+      { echo "$as_me:6155: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
