Install wrapmsvc.exe if used. Use installed wrapmsvc.exe from simage-config.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.73 .
+# From configure.in Revision: 1.74 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52b for simage v1.2.1.
 #
@@ -5291,6 +5291,7 @@ if $BUILD_WITH_MSVC; then
   # For the SuperPIMP (makensis) config file.
   win_srcdir=`cygpath -w "$srcdir"`
 
+  COIN_COMPILER=wrapmsvc
 else
   SIMAGE_EXTRA_LIBS="-lsimage${SUFFIX} $SIMAGE_EXTRA_LIBS"
 
@@ -5298,6 +5299,7 @@ else
 
   eval "simage_configure_date=\"`date +%Y%m%d`\""
 
+  COIN_COMPILER="$CC"
 fi
 
 # **************************************************************************
@@ -5387,7 +5389,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5390: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5392: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5563,7 +5565,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5566: error: ambiguous option: $1
+    { { echo "$as_me:5568: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5582,7 +5584,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5585: error: unrecognized option: $1
+  -*) { { echo "$as_me:5587: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5645,7 +5647,7 @@ do
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   "include/simage.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/simage.h" ;;
-  *) { { echo "$as_me:5648: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5650: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5809,6 +5811,7 @@ s,@win_includedir@,$win_includedir,;t t
 s,@win_libdir@,$win_libdir,;t t
 s,@win_srcdir@,$win_srcdir,;t t
 s,@simage_configure_date@,$simage_configure_date,;t t
+s,@COIN_COMPILER@,$COIN_COMPILER,;t t
 CEOF
 
 EOF
@@ -5923,7 +5926,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5926: creating $ac_file" >&5
+    { echo "$as_me:5929: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5941,7 +5944,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5944: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5947: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5954,7 +5957,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5957: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5960: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6015,7 +6018,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6018: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6021: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6026,7 +6029,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6029: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6032: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6039,7 +6042,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6042: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6045: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6156,7 +6159,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6159: $ac_file is unchanged" >&5
+      { echo "$as_me:6162: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
