Detect jasper on system. Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1074,6 +1074,7 @@ Optional Packages:
   --with-zlib=PATH        enable/disable zlib support
   --with-png=PATH         enable/disable libpng support
   --with-tiff=PATH        enable/disable libtiff support
+  --with-jasper=PATH      enable/disable jasper (JPEG 2000) support
   --with-targa            enable/disable support for Targa images
   --with-rgb              enable/disable support for RGB images
   --with-pic              enable/disable support for PIC images
@@ -5083,7 +5084,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5086 "configure"' > conftest.$ac_ext
+  echo '#line 5087 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5964,7 +5965,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5967:" \
+echo "$as_me:5968:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7021,11 +7022,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7024: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7025: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7028: \$? = $ac_status" >&5
+   echo "$as_me:7029: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7264,11 +7265,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7267: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7268: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7271: \$? = $ac_status" >&5
+   echo "$as_me:7272: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7324,11 +7325,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7327: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7328: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7331: \$? = $ac_status" >&5
+   echo "$as_me:7332: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9509,7 +9510,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9512 "configure"
+#line 9513 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9607,7 +9608,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9610 "configure"
+#line 9611 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11800,11 +11801,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11803: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11804: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11807: \$? = $ac_status" >&5
+   echo "$as_me:11808: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11860,11 +11861,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11864: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11867: \$? = $ac_status" >&5
+   echo "$as_me:11868: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13221,7 +13222,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13224 "configure"
+#line 13225 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13319,7 +13320,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13322 "configure"
+#line 13323 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14156,11 +14157,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14159: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14160: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14163: \$? = $ac_status" >&5
+   echo "$as_me:14164: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14216,11 +14217,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14219: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14220: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14223: \$? = $ac_status" >&5
+   echo "$as_me:14224: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16251,11 +16252,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16254: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16255: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16258: \$? = $ac_status" >&5
+   echo "$as_me:16259: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16494,11 +16495,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16497: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16498: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16501: \$? = $ac_status" >&5
+   echo "$as_me:16502: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16554,11 +16555,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16557: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16558: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16561: \$? = $ac_status" >&5
+   echo "$as_me:16562: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18739,7 +18740,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18742 "configure"
+#line 18743 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18837,7 +18838,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18840 "configure"
+#line 18841 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21141,7 +21142,7 @@ esac
 
   if $sim_ac_have_qt_framework; then
     sim_ac_qt_cppflags="-I$sim_ac_qt_framework_dir/QtCore.framework/Headers -I$sim_ac_qt_framework_dir/QtOpenGL.framework/Headers -I$sim_ac_qt_framework_dir/QtGui.framework/Headers -I$sim_ac_qt_framework_dir/Qt3Support.framework/Headers -F$sim_ac_qt_framework_dir"
-    sim_ac_qt_libs="-Wl,-F$sim_ac_qt_framework_dir -Wl,-framework,QtGui -Wl,-framework,QtOpenGL -Wl,-framework,QtCore -Wl,-framework,Qt3Support"
+    sim_ac_qt_libs="-Wl,-F$sim_ac_qt_framework_dir -Wl,-framework,QtGui -Wl,-framework,QtOpenGL -Wl,-framework,QtCore -Wl,-framework,Qt3Support -Wl,-framework,QtXml -Wl,-framework,QtNetwork -Wl,-framework,QtSql"
 
   else
 
@@ -24817,6 +24818,170 @@ fi
 
   # : ${sim_ac_have_libtiff=false}
   # AM_CONDITIONAL(SIMAGE_TIFF_SUPPORT, $sim_ac_have_libtiff)
+
+  # **************************************************************************
+  # Check if JPEG 2000 support is wanted (and if so, available).
+
+  : ${sim_ac_have_jasper=false}
+echo "$as_me:$LINENO: checking for jasper" >&5
+echo $ECHO_N "checking for jasper... $ECHO_C" >&6
+
+# Check whether --with-jasper or --without-jasper was given.
+if test "${with_jasper+set}" = set; then
+  withval="$with_jasper"
+  case $withval in
+  yes | "") sim_ac_want_jasper=true ;;
+  no)       sim_ac_want_jasper=false ;;
+  *)        sim_ac_want_jasper=true
+            sim_ac_jasper_path=$withval ;;
+  esac
+else
+  sim_ac_want_jasper=true
+fi;
+case $sim_ac_want_jasper in
+true)
+  $sim_ac_have_jasper && break
+  sim_ac_jasper_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_jasper_save_LDFLAGS=$LDFLAGS
+  sim_ac_jasper_save_LIBS=$LIBS
+  sim_ac_jasper_debug=false
+  test -n "`echo -- $CPPFLAGS $CFLAGS $CXXFLAGS | grep -- '-g\\>'`" &&
+    sim_ac_jasper_debug=true
+  # test -z "$sim_ac_jasper_path" -a x"$prefix" != xNONE &&
+  #   sim_ac_jasper_path=$prefix
+  sim_ac_jasper_name=jasper
+  if test -n "$sim_ac_jasper_path"; then
+    for sim_ac_jasper_candidate in \
+      `( ls $sim_ac_jasper_path/lib/jasper*.lib;
+         ls $sim_ac_jasper_path/lib/jasper*d.lib ) 2>/dev/null`
+    do
+      case $sim_ac_jasper_candidate in
+      *d.lib)
+        $sim_ac_jasper_debug &&
+          sim_ac_jasper_name=`basename $sim_ac_jasper_candidate .lib` ;;
+      *.lib)
+        sim_ac_jasper_name=`basename $sim_ac_jasper_candidate .lib` ;;
+      esac
+    done
+    sim_ac_jasper_cppflags="-I$sim_ac_jasper_path/include"
+    CPPFLAGS="$CPPFLAGS $sim_ac_jasper_cppflags"
+    sim_ac_jasper_ldflags="-L$sim_ac_jasper_path/lib"
+    LDFLAGS="$LDFLAGS $sim_ac_jasper_ldflags"
+    # unset sim_ac_jasper_candidate
+    # unset sim_ac_jasper_path
+  fi
+  sim_ac_jasper_libs="-l$sim_ac_jasper_name"
+  LIBS="$sim_ac_jasper_libs $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <jasper/jasper.h>
+int
+main ()
+{
+(void)jas_init();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_have_jasper=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  CPPFLAGS=$sim_ac_jasper_save_CPPFLAGS
+  LDFLAGS=$sim_ac_jasper_save_LDFLAGS
+  LIBS=$sim_ac_jasper_save_LIBS
+  # unset sim_ac_jasper_debug
+  # unset sim_ac_jasper_name
+  # unset sim_ac_jasper_save_CPPFLAGS
+  # unset sim_ac_jasper_save_LDFLAGS
+  # unset sim_ac_jasper_save_LIBS
+  ;;
+esac
+if $sim_ac_want_jasper; then
+  if $sim_ac_have_jasper; then
+    echo "$as_me:$LINENO: result: success ($sim_ac_jasper_libs)" >&5
+echo "${ECHO_T}success ($sim_ac_jasper_libs)" >&6
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_JASPER
+_ACEOF
+
+    SIMAGE_EXTRA_CPPFLAGS="$SIMAGE_EXTRA_CPPFLAGS $sim_ac_jasper_cppflags"
+    SIMAGE_EXTRA_LDFLAGS="$SIMAGE_EXTRA_LDFLAGS $sim_ac_jasper_ldflags"
+    SIMAGE_EXTRA_LIBS="$sim_ac_jasper_libs $SIMAGE_EXTRA_LIBS"
+    CPPFLAGS="$CPPFLAGS $sim_ac_jasper_cppflags"
+    LDFLAGS="$LDFLAGS $sim_ac_jasper_ldflags"
+    LIBS="$sim_ac_jasper_libs $LIBS"
+
+if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|JPEG 2000 image format support:Yes"
+else
+  sim_ac_configuration_settings="JPEG 2000 image format support:Yes"
+fi
+
+
+  else
+    echo "$as_me:$LINENO: result: failure" >&5
+echo "${ECHO_T}failure" >&6
+
+
+if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|JPEG 2000 image format support:No (needs jasper)"
+else
+  sim_ac_configuration_settings="JPEG 2000 image format support:No (needs jasper)"
+fi
+
+
+  fi
+else
+  echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+
+
+if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|JPEG 2000 image format support:No (needs jasper)"
+else
+  sim_ac_configuration_settings="JPEG 2000 image format support:No (needs jasper)"
+fi
+
+
+fi
+# unset sim_ac_want_jasper
+
+
+  # : ${sim_ac_have_jasper=false}
+  # AM_CONDITIONAL(SIMAGE_JASPER_SUPPORT, $sim_ac_have_libjpeg)
 
   # **************************************************************************
   # Check if TARGA support is wanted.
